// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'BrightProof', kind: "module", path: './BrightProof.html', attributes: []},
{name: 'BrightProof.SemVer', kind: "structdeclaration", path: './BrightProof/SemVer.html', attributes: []},
{name: 'BrightProof.SemVer.Build', kind: "variabledeclaration", path: './BrightProof/SemVer.Build.html', attributes: []},
{name: 'BrightProof.SemVer.Major', kind: "variabledeclaration", path: './BrightProof/SemVer.Major.html', attributes: []},
{name: 'BrightProof.SemVer.Minor', kind: "variabledeclaration", path: './BrightProof/SemVer.Minor.html', attributes: []},
{name: 'BrightProof.SemVer.nextMajor', kind: "functiondeclaration", path: './BrightProof/SemVer.nextMajor.html', attributes: ["pure", "nothrow", "nogc", "safe"]},
{name: 'BrightProof.SemVer.nextMinor', kind: "functiondeclaration", path: './BrightProof/SemVer.nextMinor.html', attributes: ["pure", "nothrow", "nogc", "safe"]},
{name: 'BrightProof.SemVer.nextPatch', kind: "functiondeclaration", path: './BrightProof/SemVer.nextPatch.html', attributes: ["pure", "nothrow", "nogc", "safe"]},
{name: 'BrightProof.SemVer.opEquals', kind: "functiondeclaration", path: './BrightProof/SemVer.opEquals.html', attributes: ["const", "pure", "nothrow", "nogc", "safe"]},
{name: 'BrightProof.SemVer.Patch', kind: "variabledeclaration", path: './BrightProof/SemVer.Patch.html', attributes: []},
{name: 'BrightProof.SemVer.PreRelease', kind: "variabledeclaration", path: './BrightProof/SemVer.PreRelease.html', attributes: []},
{name: 'BrightProof.SemVer.this', kind: "functiondeclaration", path: './BrightProof/SemVer.this.html', attributes: ["pure"]},
{name: 'BrightProof.SemVer.toString', kind: "functiondeclaration", path: './BrightProof/SemVer.toString.html', attributes: ["pure", "safe"]},
{name: 'BrightProof.SemVerException', kind: "classdeclaration", path: './BrightProof/SemVerException.html', attributes: []},
{name: 'BrightProof.SemVerException.this', kind: "functiondeclaration", path: './BrightProof/SemVerException.this.html', attributes: ["pure", "nothrow", "safe"]},
];
